// src/Illuminate/Foundation/Console/Presets/vue-stubs/ExampleComponent.vue
<template>
    <div class="card">
        <div class="card-header">
            Example Component
        </div>
        <div class="card-body">
            <p class="card-text">I'm an example component!</p>
        </div>
    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>

// src/Illuminate/Foundation/Console/Presets/react-stubs/Example.js
import React, { Component } from 'react';
import ReactDOM from 'react-dom';

export default class Example extends Component {
    render() {
        return (
            <div className="card">
                <div className="card-header">
                    Example Component
                </div>
                <div className="card-body">
                    <p className="card-text">I'm an example component!</p>
                </div>
            </div>
        );
    }
}

if (document.getElementById('example')) {
    ReactDOM.render(<Example />, document.getElementById('example'));
}
